### ISSUE TITLE
Unexpected `eval` added by Webpack

### ISSUE THREAD

**Issue by zalmoxisus** [kolodny/jsan#17]
Weirdly, after bundling the code through webpack (tried both 1 and 2 without any plugins), [this line](https://github.com/kolodny/jsan/blob/master/lib/cycle.js#L157):
```js
value[i] = utils.restore(item.$jsan, $);
```
becomes
```js
value[i] = eval(path);
```
As I see, there's nothing leading to `eval` in [`utils.restore`](https://github.com/kolodny/jsan/blob/master/lib/utils.js#L23).

@kolodny any ideas how it can appear?

**Comment by kolodny** [comment]
Huh, I seem to get the following https://gist.github.com/kolodny/60641601b679bc3e3d8afb980240f3f5

```bash
cd /tmp
git clone https://github.com/kolodny/jsan/
npm i webpack
./node_modules/.bin/webpack index.js output.js
```

**Comment by zalmoxisus** [comment]
I'm sorry for the wrong issue! It's from [`cycle.js`](https://github.com/dscape/cycle/blob/master/cycle.js#L145). I was confused that it was the only difference in this part of code :-/

**Comment by kolodny** [comment]
No worries. It looked like `jsan` to me too. Both projects are forked off the same repo.
