### ISSUE TITLE
Skip data which throws on `value.toJSON`

### ISSUE THREAD

**Issue by zalmoxisus** [kolodny/jsan#18]
To skip data we don't have access to, we could add a `try-catch` in https://github.com/kolodny/jsan/blob/638607199b4dc5385443c6c22af0b2dc7c6e0f09/lib/cycle.js#L87 

It would solve issues like https://github.com/zalmoxisus/redux-devtools-extension/issues/407, but not sure it's good to swallow exceptions.

**Comment by kolodny** [comment]
@zalmoxisus Can you provide a simple example to reproduce the error, I can't seem to cause an error to happen

**Comment by kolodny** [comment]
Closing for now, feel free to reopen if the problem persists
