### ISSUE TITLE
jsan.stringify space argument not working

### ISSUE THREAD

**Issue by jaydenseric** [kolodny/jsan#23]
The third `space` argument for `jsan.stringify` is not implemented: https://github.com/kolodny/jsan/blob/master/lib/index.js#L3

Surely it could be passed into the internal `JSON.stringify` call here: https://github.com/kolodny/jsan/blob/master/lib/index.js#L21

My use-case is to flatten an object with circular references for snapshot testing. For diffing, a formatted string is far better than all on one line.

**Comment by kolodny** [comment]
Thanks for the bug report. A fix is out in `v3.1.11`
