### ISSUE TITLE
Support for Immutable.js

### ISSUE THREAD

**Issue by zalmoxisus** [kolodny/jsan#4]
As reported in https://github.com/zalmoxisus/redux-devtools-extension/issues/67, "deep" serialization breaks immutable data.

So, `jsan.stringify(obj)` will return  for `... "todoList": immutable.List()`
```js
{"monitorState":{},"actionsById":{"0":{"type":"PERFORM_ACTION","action":{"type":"@@INIT"},"timestamp":1456848558040}},"nextActionId":1,"stagedActionIds":[0],"skippedActionIds":[],"currentStateIndex":0,"computedStates":
[{"state":{"todos":{"activeFilter":"all",

"todoList":[]

}}}]
}
```
While `jsan.stringify(obj, null, null, true)` returns
```js
{"monitorState":{},"actionsById":{"0":{"type":"PERFORM_ACTION","action":{"type":"@@INIT"},"timestamp":1456848558040}},"nextActionId":1,"stagedActionIds":[0],"skippedActionIds":[],"committedState":{"$jsan":"u"},"currentStateIndex":0,"computedStates":[{"state":{"todos":{"activeFilter":"all",

"todoList":{"size":0,"_origin":0,"_capacity":0,"_level":5,"_root":{"$jsan":"u"},"_tail":{"$jsan":"u"},"__ownerID":{"$jsan":"u"},"__hash":{"$jsan":"u"},"__altered":false}}},"error":{"$jsan":"u"}}

]}
```

Is there a way to support Immutable.js also on "deep" serialization or we should use only `jsan.stringify(obj)` in this case? If not, I'm going to just let the users to choose which type of serialization to use.

**Comment by kolodny** [comment]
I just pushed `3.1.1` which should fix this.

**Comment by kolodny** [comment]
https://github.com/zalmoxisus/redux-devtools-extension/issues/67#issuecomment-190901034
